version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout
      - install_deps
      - run:
          name: run tests
          command: |
            npm run unit-tests
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - store_artifacts:
          path: ./
  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      APP_PORT: 4000
    steps:
      - checkout
      - install_deps
      - run:
          name: run integration test
          command: |
            npm run integration-tests

  sast:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Run NodeJsScan
          command: |
            nodejsscan -d ./

workflows:
  build-and-packge:
    jobs:
      - ci-build
      - integration-tests
      - pack:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - master
      - sast:
          requires:
            - integration-tests
            